### ISSUE TITLE
running parallel with spring configuration

### ISSUE THREAD

**Issue by nadavvitri** [csabagabor/junit4-parallel-runner-intellij-plugin#5]
Hi, 
first thank you for the amazing plugin :) 
When I'm trying to run test that using spring configuration (and @Autowired) in parallel I'm getting some errors. I think it's related to the Autowired.
it's possible to urn such test in parallel?

**Comment by csabagabor** [comment]
Hello,
it's definitely possible to run tests  which make use of  **@Autowired**. There are 2 possible causes why issues may arise:

1. if you reuse the Spring context between your integration tests, then the Spring app may not start up correctly at all. I have seen such errors myself, fixing these is not straight forward.

2. If you don't reuse the Spring context, issues may arise if the autowired beans connect to some external services (databases, message brokers etc.), or if they expose some ports.....In that case the app needs to be modified in order to be able to run the tests in parallel. This is not always possible, unfortunately...



I don't reccomend running **integration** tests in parallel, though. The speedup is negligible ususally and tests may become flaky especially if they store data in a database. Running integration tests in a forked mode where each JVM has its separate database, message broker etc. may be a better idea. For **unit** tests, where we don't have Autowired beans, using this plugin will definitely result in a large speedup and such issues shouldn't happen.

**Comment by nadavvitri** [comment]
great. thanks!
